allowBuilds:
  esbuild: false
  puppeteer: true
minimumReleaseAgeExclude:
  - '@fimbul-works/hash@1.2.1'
  - '@oxc-parser/binding-android-arm-eabi@0.149.0'
  - '@oxc-parser/binding-android-arm64@0.149.0'
  - '@oxc-parser/binding-darwin-arm64@0.149.0'
  - '@oxc-parser/binding-darwin-x64@0.149.0'
  - '@oxc-parser/binding-freebsd-x64@0.149.0'
  - '@oxc-parser/binding-linux-arm-gnueabihf@0.149.0'
  - '@oxc-parser/binding-linux-arm-musleabihf@0.149.0'
  - '@oxc-parser/binding-linux-arm64-gnu@0.149.0'
  - '@oxc-parser/binding-linux-arm64-musl@0.149.0'
  - '@oxc-parser/binding-linux-ppc64-gnu@0.149.0'
  - '@oxc-parser/binding-linux-riscv64-gnu@0.149.0'
  - '@oxc-parser/binding-linux-riscv64-musl@0.149.0'
  - '@oxc-parser/binding-linux-s390x-gnu@0.149.0'
  - '@oxc-parser/binding-linux-x64-gnu@0.149.0'
  - '@oxc-parser/binding-linux-x64-musl@0.149.0'
  - '@oxc-parser/binding-openharmony-arm64@0.149.0'
  - '@oxc-parser/binding-win32-arm64-msvc@0.149.0'
  - '@oxc-parser/binding-win32-ia32-msvc@0.149.0'
  - '@oxc-parser/binding-win32-x64-msvc@0.149.0'
  - '@oxc-project/types@0.149.0'
  - '@types/node@26.5.0'
  - oxc-parser@0.149.0
