import { decodeBase62 } from "./encode-number";

/**
 * Extracts the creation timestamp from a UID.
 *
 * @param {string} uid - A unique identifier generated by `uid()`
 * @returns {number} The creation time as milliseconds
 * @throws {Error} On invalid Base-62 character
 */
export const uidTime = (uid: string): number => decodeBase62(uid.split("-")[0]);
