import { BASE62_ALPHABET, decodeBase62, encodeBase62 } from "./base62";
import { isServer } from "./environment/is-server";

/**
 * Generates a random base-62 string of specified length.
 *
 * @param {number} length - The length of the random string to generate
 * @param {() => number} [random=Math.random] - The random number generator to use
 * @returns {string} The random base-62 string
 */
const randomString = (length: number, random = Math.random): string => {
  let result = "";
  for (let i = 0; i < length; i++) {
    result += BASE62_ALPHABET[Math.floor(random() * 62)];
  }
  return result;
};

/**
 * Generates a unique identifier (UID).
 *
 * The UID is time-sorted and consists of three parts separated by hyphens:
 * - Timestamp: Time when the UID was created (sortable)
 * - Process ID: Process identifier (or random if not available)
 * - Random: High-entropy random component
 *
 * @returns {string} A unique identifier string (approximately 20 characters)
 */
export const uid = (): string =>
  [encodeBase62(Date.now()), isServer() ? encodeBase62(process.pid) : randomString(3), randomString(8)].join("-");

/**
 * Extracts the creation timestamp from a UID.
 *
 * @param {string} uid - A unique identifier generated by `uid()`
 * @returns {number} The creation time as milliseconds
 * @throws {Error} On invalid Base-62 character
 */
export const uidTime = (uid: string): number => decodeBase62(uid.split("-")[0]);
