import { decodeBase62 } from "./base62";

/**
 * Extracts the creation timestamp from a UID.
 *
 * @param {string} uid - A unique identifier generated by `uid()`
 * @returns {number} The creation time as milliseconds
 * @throws {Error} On invalid Base-62 character
 *
 * @example
 * ```typescript
 * import { uid, uidTime } from '@fimbul-works/seidr';
 *
 * const id = uid(); // "v67JXa8-2Mj-Ukd7o93r"
 * const createdAt = uidTime(id); // number
 * console.log(new Date(createdAt).toISOString()); // "2024-12-22T..."
 * ```
 *
 * @example
 * Sorting by creation time
 * ```typescript
 * const items = [
 *   { id: uid(), text: "First" },
 *   { id: uid(), text: "Second" }
 * ];
 *
 * // Sort by creation time
 * items.sort((a, b) => uidTime(a.id).getTime() - uidTime(b.id).getTime());
 * ```
 */
export const uidTime = (uid: string): number => decodeBase62(uid.split("-")[0]);
