import { BASE62_ALPHABET, RADIX } from "./uid";

/**
 * Decodes a base-62 string to a number.
 */
const decodeBase62 = (str: string): number => {
  let result = 0;
  for (let i = 0; i < str.length; i++) {
    const digit = BASE62_ALPHABET.indexOf(str[i]);
    if (digit === -1) throw new Error(`Invalid base-62 character: ${str[i]}`);
    result = result * RADIX + digit;
  }
  return result;
};

/**
 * Extracts the creation timestamp from a UID.
 *
 * @param uid - A unique identifier generated by `uid()`
 * @returns The creation time as milliseconds
 *
 * @example
 * ```typescript
 * import { uid, uidTime } from '@fimbul-works/seidr';
 *
 * const id = uid(); // "v67JXa8-2Mj-Ukd7o93r"
 * const createdAt = uidTime(id); // number
 * console.log(new Date(createdAt).toISOString()); // "2024-12-22T..."
 * ```
 *
 * @example
 * Sorting by creation time
 * ```typescript
 * const items = [
 *   { id: uid(), text: "First" },
 *   { id: uid(), text: "Second" }
 * ];
 *
 * // Sort by creation time
 * items.sort((a, b) => uidTime(a.id).getTime() - uidTime(b.id).getTime());
 * ```
 */
export const uidTime = (uid: string): number => decodeBase62(uid.split("-")[0]);
