export const TAGLINES: readonly [string, string[]][] = [
  [
    "Seiðr, Actually",
    [
      "A love letter to reactive state, written under duress.",
      "Committed to components. Emotionally and otherwise.",
      "We were on a break. Then I refactored everything.",
      "No magic. Just JavaScript wearing a suspicious hat.",
      "It's not witchcraft if the tests pass.",
      "Any sufficiently small framework is indistinguishable from magic. Or a mistake.",
    ],
  ],
  [
    "Signals of Affection",
    [
      "It's not clingy if it's reactive.",
      "I'll notify you. That's a promise, not a Promise.",
      "Subscribed to your changes since day one.",
      "I compute you, therefore I am.",
      "It's probably fine. We have tests.",
      "Reactive enough to know when you've changed your mind.",
      "Seeded with love. Reproducible with spite.",
    ],
  ],
  [
    "Bundle of Nerves",
    [
      "5 kB and every gram of it emotional baggage.",
      "Tree-shaken, not stirred.",
      "We minified the code, not the ambition.",
      "Small enough to fit in your anxiety.",
      "Every unused export was a friend we lost along the way.",
      "Your network connection has suffered enough.",
      "Every byte has a job. Some have emotional baggage.",
    ],
  ],
  [
    "Effectively Speaking",
    [
      "Side effects may include: fewer side effects.",
      "Cleanup functions: the emotional labor of the framework world.",
      "We run once, we run right.",
      "Dependency arrays are just love languages for functions.",
      "Every effect has consequences. We accept ours.",
      "Fine-grained reactivity for people with fine-grained anxieties.",
      "We put the 'fun' in functional programming. Legal says we can't prove this.",
    ],
  ],
  [
    "State of the Art(-ish)",
    [
      "Fine-grained, mostly on purpose.",
      "No virtual DOM. Just craft and vibes.",
      "Surgical updates. Occasionally overkill.",
      "Pure functions, impure motives.",
      "Cutting-edge, in a kilobyte-conscious way.",
      "We reinvented the wheel. It's smaller now.",
      "Hydration without the identity crisis.",
      "The server rendered it. The client merely nodded.",
    ],
  ],
  [
    "A Few kB of Your Time",
    [
      "Zero-build. Zero regrets. Occasional exceptions.",
      "Seidr ships less, so you'll wait less.",
      "Every byte has to justify its existence.",
      "Lean by design. Occasionally lean by accident.",
      "Small doesn't mean meaningless. Sometimes, small is simply where growth begins.",
      "Can I offer you a small framework in these trying times?",
      "Small enough to make your bundler feel inadequate.",
      "Kilobytes are just grams for software.",
    ],
  ],
  [
    "Less Framework, More Web",
    [
      "The browser already knows how to render things.",
      "No virtual DOM. We checked.",
      "Let the platform do some of the work.",
      "Because the web is already pretty good at being the web.",
      "Performance budgets are more fun when you actually meet them.",
      "Made of mostly code and unreasonable opinions.",
      "Bytes are expensive. Feelings are free.",
      "We put the framework on a byte diet.",
      "Smaller than the thing everyone says is small.",
    ],
  ],
  [
    "The DOM Awakens",
    [
      "Turns out it was useful all along.",
      "The ancient API returns for one final battle.",
      "No abstraction was necessary for this scene.",
      "Direct manipulation, carefully applied.",
      "The client already knows. We brought receipts.",
      "React asked for a virtual DOM. We asked for a real one and a coffee.",
    ],
  ],
  [
    "Framework, Unframeworked",
    [
      "All the useful bits. None of the ceremony.",
      "The framework equivalent of removing three layers of abstraction.",
      "Less machinery between you and the browser.",
      "Because sometimes the abstraction is the problem.",
      "A framework that knows when to get out of the way.",
      "Framework fatigue? We prefer framework anemia.",
      "All the framework you need. Most of the framework you don't.",
    ],
  ],
] as const;
